### ISSUE TITLE
ResultSetFilter data type inconsistency

### ISSUE THREAD

**Issue by mbt1** [tSQLt-org/tSQLt#145]
code to reproduce the issue:

```
EXEC tSQLt.NewTestClass xxxxx
GO
CREATE PROCEDURE xxxxx.testRShSV
AS
BEGIN
  CREATE TABLE xxxxx.xtwv(Id INT,sv SQL_VARIANT)
  INSERT xxxxx.xtwv(id,sv)VALUES(1,CAST(13 AS INT))
  INSERT xxxxx.xtwv(id,sv)VALUES(2,CAST('xx' AS VARCHAR(13)))
  INSERT xxxxx.xtwv(id,sv)VALUES(3,CAST('45' AS CHAR(2)))
  INSERT xxxxx.xtwv(id,sv)VALUES(4,CAST(NULL AS DECIMAL))
  
  SELECT *,SQL_VARIANT_PROPERTY(sv,'BaseType ') FROM xxxxx.xtwv;
  
  INSERT INTO xxxxx.xtwv
  EXEC tSQLt.ResultsetFilter 1, 'SELECT * FROM xxxxx.xtwv;';

  SELECT *,SQL_VARIANT_PROPERTY(sv,'BaseType ') FROM xxxxx.xtwv;

END
GO
EXEC tSQLt.Run xxxxx;
```

**Comment by clifton-collins3iii** [comment]
Is the following error related to this bug or a new bug?

Msg 6522, Level 16, State 1, Procedure tSQLt.ResultSetFilter, Line 0 [Batch Start Line 0]
A .NET Framework error occurred during execution of user-defined routine or aggregate "ResultSetFilter": 
System.Data.SqlClient.SqlException: Implicit conversion from data type datetime to int is not allowed. Use the CONVERT function to run this query.
System.Data.SqlClient.SqlException: 
   at Microsoft.SqlServer.Server.SmiEventSink_Default.DispatchMessages(Boolean ignoreNonFatalMessages)
   at Microsoft.SqlServer.Server.SqlPipe.SendResultsStart(SqlDataRecord record)
   at tSQLtCLR.ResultSetFilter.sendResultsetRecords(SqlDataReader dataReader)
   at tSQLtCLR.ResultSetFilter.sendSelectedResultSetToSqlContext(SqlInt32 resultsetNo, SqlString command)
   at tSQLtCLR.StoredProcedures.ResultSetFilter(SqlInt32 resultSetNo, SqlString command)
.

without the insert into the following produces one resultset as expected:
**Exec tSQLt.ResultSetFilter 1, 'EXEC dbo.spr_sel_BolusHistoryByUserID** 
**Exec tSQLt.ResultSetFilter 2, 'EXEC dbo.spr_sel_BolusHistoryByUserID** 

with the insert into the following produces the exception above:
Insert Into actual
Exec tSQLt.ResultSetFilter 1, 'EXEC dbo.spr_sel_BolusHistoryByUserID 

CREATE TABLE [dbo].[actual](
	[BolusRequestID] [int] NOT NULL,
	[BolusRequestDateTime] [varchar](23) NOT NULL,
	[UploadID] [int] NOT NULL,
	[IndexID] [int] NOT NULL,
	[BolusID] [numeric](8, 3) NOT NULL,
	[BolusTypeID] [int] NOT NULL,
	[BolusType] [varchar](4) NOT NULL,
	[BolusTypeDesc] [varchar](4) NOT NULL,
	[OptionTypeID] [int] NOT NULL,
	[OptionTypeDesc] [nvarchar](8) NOT NULL,
	[IsStandard] [int] NOT NULL,
	[IsExtended] [int] NOT NULL,
	[IsQuick] [int] NOT NULL,
	[BG] [int] NOT NULL,
	[IOB] [numeric](15, 14) NOT NULL,
	[StandardPercent] [int] NOT NULL,
	[Duration] [int] NOT NULL,
	[CarbSize] [int] NOT NULL,
	[IsOverride] [int] NOT NULL,
	[CorrectionBolusIncluded] [int] NOT NULL,
	[TargetBG] [int] NOT NULL,
	[CorrectionFactor] [int] NOT NULL,
	[FoodBolusSize] [int] NOT NULL,
	[CorrectionBolusSize] [int] NOT NULL,
	[ActualTotalBolusRequested] [int] NOT NULL,
	[DeclinedCorrection] [int] NOT NULL,
	[BolusActivationDateTime] [varchar](23) NOT NULL,
	[BolusCompletionID] [int] NOT NULL,
	[BolusCompletionDateTime] [varchar](23) NOT NULL,
	[BolusCompletionStatusID] [int] NOT NULL,
	[BolusCompletionStatusType] [varchar](9) NOT NULL,
	[BolusCompletionDesc] [varchar](9) NOT NULL,
	[BCIOB] [numeric](15, 14) NOT NULL,
	[InsulinDelivered] [int] NOT NULL,
	[InsulinRequested] [int] NOT NULL,
	[BolusActivationID] [int] NULL,
	[BolusActivationIndexID] [int] NULL,
	[BolexSize] [int] NULL,
	[BolexActivationDateTime] [int] NULL,
	[BolexCompletionID] [int] NULL,
	[BolexCompletionIndexID] [int] NULL,
	[ExtendedInsulinDelivered] [int] NULL,
	[BolexCompletionStatusID] [int] NULL,
	[BolexCompletionStatusType] [int] NULL,
	[BolusCompletionDesc_44] [int] NULL,
	[BolexCompletionDateTime] [int] NULL,
	[InsulinRequested_46] [int] NULL
)

**Comment by clifton-collins3iii** [comment]
A follow up on the previous message.
The second result inserts successfully into actual2


Insert Into actual2
Exec tSQLt.ResultSetFilter 2, 'EXEC dbo.spr_sel_BolusHistoryByUserID ''EC3B805E-7B98-417C-A85F-7CADF58A7BB5'',''2019-12-18'',''2019-12-18'',''RAW'',NULL,1,NULL,0'

CREATE TABLE [dbo].[actual2](
	[@Type] [varchar](3) NOT NULL,
	[EventID] [int] NOT NULL,
	[BolusID] [int] NULL,
	[EventDateTime] [varchar](23) NOT NULL,
	[IOB] [numeric](3, 2) NOT NULL
)
