### ISSUE TITLE
SuppressOutput doesn't catch SqlException

### ISSUE THREAD

**Issue by Jevonius** [tSQLt-org/tSQLt#39]
Hi, there is not much documentation around `SuppressOutput`, so it's possible I'm not using it quite as intended. I am using SuppressOutput to mean "I don't care about the outcome of the execution, even exceptions", but a call to RAISERROR throws an exception that the implementation of SuppressOutput doesn't catch and handle:
```
[TestSchema].[test My RAISEERROR Test] failed: (Error) A .NET Framework error occurred during execution of user-defined routine or aggregate "SuppressOutput": 
System.Data.SqlClient.SqlException: This is the RAISERROR message
System.Data.SqlClient.SqlException: 
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnectionSmi.EventSink.DispatchMessages(Boolean ignoreNonFatalMessages)
   at System.Data.SqlClient.SqlDataReaderSmi.InternalNextResult(Boolean ignoreNonFatalMessages)
   at System.Data.SqlClient.SqlDataReaderSmi.NextResult()
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderSmi(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at tSQLtCLR.TestDatabaseFacade.executeCommand(SqlString Command)
   at tSQLtCLR.StoredProcedures.SuppressOutput(SqlString command)
.[16,1]{SuppressOutput,0}
```

My expectation was that the exception would be caught and ignored, and execution would continue rather than failing the test as Error.

I've had a quick look through the code, and I *think* this would be handled by modifying the following to include a try/catch block:
https://github.com/tSQLt-org/tSQLt/blob/82ea5f44b3f756980dfe68db1cdd3116685885fc/tSQLtCLR/tSQLtCLR/OutputCaptor.cs#L25-L28

I haven't tested it, but I suspect that `CaptureOutput` has a similar issue with exceptions - an alternative solution might be to modify the implementation of `testDatabaseFacade.executeCommand` to capture exceptions and log them to the `InfoMessage` (or similar) property.

Would be happy to give either of these a shot, but before I spend the time I'd like to understand what the preferred solution should be.

**Comment by mbt1** [comment]
Jevon,

tSQLt.SuppressOutput is meant to catch and discard output of procedures
cause by things like print statements. It was not intended to catch errors.
I also don't think that a suppress error functionality would be a good
thing to have as it would muddy what is going on. SQL Server (or .NET) for
that matter does not truly allow to ignore exceptions. The way to make it
work (as you mention) would be a try catch block. however, I believe that
that behavior needs to be blatantly obvious in a test - meaning, I advocate
to just put the try..catch directly in the test.

I could see that add a @SuppressErrors parameter to tSQLt.SuppressOutput,
but I'm a little torn on it.
Anybody else wants to chime in?


Thanks,

Sebastian

**Comment by Jevonius** [comment]
Hi Sebastian,

Thanks for your reply; I agree supressing exceptions feels odd, however I think there is some inconsistency in pure T-SQL versus CLR handling of errors, depending on the severity. Here's a bit of background around what I'm trying to achieve, and why I think there is *something* wrong with the CLR code, even if the solution suggested above isn't exactly the right one...

Within our BI-related code, we have a stored procedure that does a number of things based on a source table. Simplified:
1) Create placeholder rows in table `ABC`
2) Check for matched values in table `DEF` (think manual referential integrity) and error if mismatched
3) Insert the data into the target table

I had tests working for step 1, but then upon implementing step 2, the tests for step 1 started failing with the exception above, whereas the tests for step 2 using `ExpectException` work fine. Herein lies the inconsistency: `ExpectException` appears to be pure T-SQL, whereas `SuppressOutput` is CLR - RAISERROR is only causing issues when dipping into CLR, and the 'error' is effectively miscategorised.

You reply reminded me about the Severity parameter. I was originally using 16, but changing it to 10 or below allowed `SuppressOutput` to function as expected. Reading up on [RAISERROR](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/raiserror-transact-sql), severities above 10 cause execution to jump to a catch block; in the case of CLR, 0-10 does not raise an exception, 11+ does. For us, a value >10 is the correct behaviour.

SqlException has a Class property which corresponds to the Severity - perhaps the 'catch' logic described above could be intelligent and tweak its behaviour based on the Severity/Class, per the RAISERROR documentation, which suggests `SuppressOutput` should be able to safely ignore exceptions (and conversely `CaptureOutput` could catch and log them) if the Class is less than 20.

Optionally, as you suggest, this changed behaviour could be switched via a 'CaptureExceptions` (or perhaps even a capture level?) parameter on both methods.

**Comment by Jevonius** [comment]
I just tested a bit further, errors with a severity <=10 are effectively just warnings and stop `ExpectException` tests working.
